### ISSUE TITLE
Please review

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/zipkin-api#1]
Hey @adriancole I've started writing the spec. I'm not sure if I understood the API correctly or got stuff correct. Please paste the YAML file in Swagger Editor and take look and let me know what you think.

**Comment by codefromthecrypt** [comment]
next time: easier to do with pull request as I can make line comments that
way :P

**Comment by codefromthecrypt** [comment]
first thing I noticed in the yaml is that it is using a path parameter, not a query parameter for serviceName. probably want to doublecheck by either looking at my curl commands or testing on your own against zipkin as it will prevent these sorts of typos.

**Comment by codefromthecrypt** [comment]
also, and also mentioned in my doc, there is not standard error type, so let's not add one in the doc as it will mislead people

**Comment by codefromthecrypt** [comment]
question about markup.. declaring ServiceName type, when a response is an array of strings, seems laborious and makes for unnecessary navigation (especially as it is only used once). Is there an easier way to deal with array string responses in this format?

**Comment by codefromthecrypt** [comment]
I could see ServiceName type being useful, if it were tied both to the response of the get service names query and also the serviceName input parameter.. is there a way to do that?

**Comment by mohsen1** [comment]
No, a query parameter can not have a schema.

**Comment by mohsen1** [comment]
Ok I've fixed issues you've addressed. I'll continue adding more details to spec.

**Comment by mohsen1** [comment]
I've added the models. Please take a look. I'm not sure about names I've given to each model.

**Comment by mohsen1** [comment]
Ok I went through all of the endpoints and models. Please review.

**Comment by karlunho** [comment]
Can you post a link to API studio ;-)

**Comment by mohsen1** [comment]
@karlunho Just paste the YAML file there.

**Comment by codefromthecrypt** [comment]
PS might be latency related (as studio isn't fast from this part of the
world), but when I paste it, the right-hand-side doesn't look useful.. ex
only shows this.. Ex clicking on List all.. does nothing

[image: Inline image 1]

**Comment by codefromthecrypt** [comment]
ok. let's move over to https://github.com/openzipkin/zipkin-api

can you raise the initial import as a pull request? That way, we don't have to taint the gitlog of master with lots of chatter? plus, easier to make inline comments.

**Comment by prabhatjha** [comment]
Mohsen: Pls go ahead and send the PR since you did the bulk of work.

Alan: You can see this API on Studio at
http://playground.apistudio.io/265dd9e4-86a8-433b-a446-512ef16b47ac/#/  and
it's wired to server that Adrian "secretly" has created. Since it does not
have CORS, we can hit it from Studio itself but resulting curl commands
work.

**Comment by mohsen1** [comment]
Done https://github.com/openzipkin/zipkin-api/pull/1
